"""se agrego codigo a materia

Revision ID: 5260af6aa8e1
Revises: 3947b7b3e734
Create Date: 2025-02-19 05:01:20.051689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5260af6aa8e1'
down_revision = '3947b7b3e734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
