"""agregado resumen

Revision ID: dd0b11410e96
Revises: ed4fada308c2
Create Date: 2025-02-21 04:18:56.592627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0b11410e96'
down_revision = 'ed4fada308c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('instancia', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resumen_id', sa.Integer(), nullable=True))
        batch_op.alter_column('examen_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'resumen', ['resumen_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('examen_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('resumen_id')

    op.drop_table('resumen')
    # ### end Alembic commands ###
